#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp01
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="qlsv")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_hocsinh(tbl_hocsinh instance);
    partial void Updatetbl_hocsinh(tbl_hocsinh instance);
    partial void Deletetbl_hocsinh(tbl_hocsinh instance);
    partial void Inserttbl_lophoc(tbl_lophoc instance);
    partial void Updatetbl_lophoc(tbl_lophoc instance);
    partial void Deletetbl_lophoc(tbl_lophoc instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::WindowsFormsApp01.Properties.Settings.Default.qlsvConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_hocsinh> tbl_hocsinhs
		{
			get
			{
				return this.GetTable<tbl_hocsinh>();
			}
		}
		
		public System.Data.Linq.Table<tbl_lophoc> tbl_lophocs
		{
			get
			{
				return this.GetTable<tbl_lophoc>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_hocsinh")]
	public partial class tbl_hocsinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _masv;
		
		private string _hovaten;
		
		private System.Nullable<bool> _gioitinh;
		
		private System.Nullable<System.DateTime> _ngaysinh;
		
		private System.Nullable<int> _malop;
		
		private EntityRef<tbl_lophoc> _tbl_lophoc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnmasvChanging(string value);
    partial void OnmasvChanged();
    partial void OnhovatenChanging(string value);
    partial void OnhovatenChanged();
    partial void OngioitinhChanging(System.Nullable<bool> value);
    partial void OngioitinhChanged();
    partial void OnngaysinhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaysinhChanged();
    partial void OnmalopChanging(System.Nullable<int> value);
    partial void OnmalopChanged();
    #endregion
		
		public tbl_hocsinh()
		{
			this._tbl_lophoc = default(EntityRef<tbl_lophoc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masv", DbType="VarChar(20)")]
		public string masv
		{
			get
			{
				return this._masv;
			}
			set
			{
				if ((this._masv != value))
				{
					this.OnmasvChanging(value);
					this.SendPropertyChanging();
					this._masv = value;
					this.SendPropertyChanged("masv");
					this.OnmasvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hovaten", DbType="VarChar(20)")]
		public string hovaten
		{
			get
			{
				return this._hovaten;
			}
			set
			{
				if ((this._hovaten != value))
				{
					this.OnhovatenChanging(value);
					this.SendPropertyChanging();
					this._hovaten = value;
					this.SendPropertyChanged("hovaten");
					this.OnhovatenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="Bit")]
		public System.Nullable<bool> gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="Date")]
		public System.Nullable<System.DateTime> ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this.OnngaysinhChanging(value);
					this.SendPropertyChanging();
					this._ngaysinh = value;
					this.SendPropertyChanged("ngaysinh");
					this.OnngaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_malop", DbType="Int")]
		public System.Nullable<int> malop
		{
			get
			{
				return this._malop;
			}
			set
			{
				if ((this._malop != value))
				{
					if (this._tbl_lophoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmalopChanging(value);
					this.SendPropertyChanging();
					this._malop = value;
					this.SendPropertyChanged("malop");
					this.OnmalopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_lophoc_tbl_hocsinh", Storage="_tbl_lophoc", ThisKey="malop", OtherKey="id", IsForeignKey=true)]
		public tbl_lophoc tbl_lophoc
		{
			get
			{
				return this._tbl_lophoc.Entity;
			}
			set
			{
				tbl_lophoc previousValue = this._tbl_lophoc.Entity;
				if (((previousValue != value) 
							|| (this._tbl_lophoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_lophoc.Entity = null;
						previousValue.tbl_hocsinhs.Remove(this);
					}
					this._tbl_lophoc.Entity = value;
					if ((value != null))
					{
						value.tbl_hocsinhs.Add(this);
						this._malop = value.id;
					}
					else
					{
						this._malop = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_lophoc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_lophoc")]
	public partial class tbl_lophoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _malop;
		
		private string _tenlop;
		
		private string _ghichu;
		
		private EntitySet<tbl_hocsinh> _tbl_hocsinhs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnmalopChanging(string value);
    partial void OnmalopChanged();
    partial void OntenlopChanging(string value);
    partial void OntenlopChanged();
    partial void OnghichuChanging(string value);
    partial void OnghichuChanged();
    #endregion
		
		public tbl_lophoc()
		{
			this._tbl_hocsinhs = new EntitySet<tbl_hocsinh>(new Action<tbl_hocsinh>(this.attach_tbl_hocsinhs), new Action<tbl_hocsinh>(this.detach_tbl_hocsinhs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_malop", DbType="VarChar(20)")]
		public string malop
		{
			get
			{
				return this._malop;
			}
			set
			{
				if ((this._malop != value))
				{
					this.OnmalopChanging(value);
					this.SendPropertyChanging();
					this._malop = value;
					this.SendPropertyChanged("malop");
					this.OnmalopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenlop", DbType="VarChar(20)")]
		public string tenlop
		{
			get
			{
				return this._tenlop;
			}
			set
			{
				if ((this._tenlop != value))
				{
					this.OntenlopChanging(value);
					this.SendPropertyChanging();
					this._tenlop = value;
					this.SendPropertyChanged("tenlop");
					this.OntenlopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghichu", DbType="VarChar(50)")]
		public string ghichu
		{
			get
			{
				return this._ghichu;
			}
			set
			{
				if ((this._ghichu != value))
				{
					this.OnghichuChanging(value);
					this.SendPropertyChanging();
					this._ghichu = value;
					this.SendPropertyChanged("ghichu");
					this.OnghichuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_lophoc_tbl_hocsinh", Storage="_tbl_hocsinhs", ThisKey="id", OtherKey="malop")]
		public EntitySet<tbl_hocsinh> tbl_hocsinhs
		{
			get
			{
				return this._tbl_hocsinhs;
			}
			set
			{
				this._tbl_hocsinhs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_hocsinhs(tbl_hocsinh entity)
		{
			this.SendPropertyChanging();
			entity.tbl_lophoc = this;
		}
		
		private void detach_tbl_hocsinhs(tbl_hocsinh entity)
		{
			this.SendPropertyChanging();
			entity.tbl_lophoc = null;
		}
	}
}
#pragma warning restore 1591
